#!/usr/bin/env bash
set -euo pipefail
set -x
dir="$(dirname "$(readlink -f "$0")")"

cd "$dir"

TVM_PKG_VERSION="$(cat tvm_version.txt)"

# Trick for installing libLLVM along libtvm.so
# Set TVM_LIBRARY_PATH and install tvm with ninja install
# Set LLVM_LIB_LIST along with corresponding patch to copy libLLVM.so
TVM_INSTALL_PREFIX="/tmp/project/tvm/install"
TVM_LIBRARY_PATH="$TVM_INSTALL_PREFIX/lib"
TVM_EXTRA_LIB_LIST="$TVM_INSTALL_PREFIX/lib/libLLVM.so"

BUILD_PLATFORM="${BUILD_PLATFORM:-linux}"

CIBW_PLATFORM='linux'
CIBW_ARCHS='x86_64'
CIBW_BUILD='cp3*-manylinux*'
CIBW_MANYLINUX_IMAGE='manylinux_2_28'
CIBW_CONTAINER_ENGINE_ARG="" 

BUILD_LLVM_DEBUG_TARGET="${BUILD_LLVM_DEBUG_TARGET:-}"
BUILD_LLVM_CLEAN_BUILD_DIR="${BUILD_LLVM_CLEAN_BUILD_DIR:-1}"
CIBW_DEBUG_KEEP_CONTAINER="${CIBW_DEBUG_KEEP_CONTAINER:-0}"
BUILD_LLVM_COMPONENTS=""

CIBW_BEFORE_BUILD="rm -rf dist build *egg-info"
CIBW_TEST_COMMAND='{project}/tests/test-graph.sh'
CIBW_BEFORE_ALL="env BUILD_PLATFORM=$BUILD_PLATFORM ./install-build-tools.sh && env BUILD_PLATFORM=$BUILD_PLATFORM ./install-llvm.sh && env BUILD_PLATFORM=$BUILD_PLATFORM ./build-tvm.sh"

if [ "$BUILD_PLATFORM" = "linux" ]; then
    DOCKER_ARGS=""
    CIBW_CONTAINER_ENGINE_ARG="CIBW_CONTAINER_ENGINE=docker;create_args:$DOCKER_ARGS"
elif [ "$BUILD_PLATFORM" = "darwin" ]; then
    CIBW_PLATFORM='macos'
    CIBW_ARCHS='arm64'
    CIBW_BUILD='cp3*-macosx_arm64'
    CIBW_MANYLINUX_IMAGE="" 
    TVM_EXTRA_LIB_LIST="$TVM_INSTALL_PREFIX/lib/libLLVM.dylib"
else
    echo "Error: Unknown BUILD_PLATFORM '$BUILD_PLATFORM'. Must be 'linux' or 'darwin'."
    exit 1
fi

ENV_VARS=(
    CIBW_PLATFORM="$CIBW_PLATFORM"
    CIBW_ARCHS="$CIBW_ARCHS"
    MACOSX_DEPLOYMENT_TARGET=15.0
    CIBW_BUILD="$CIBW_BUILD"
    CIBW_PROJECT_REQUIRES_PYTHON='>=3.10'
    CIBW_MANYLINUX_X86_64_IMAGE="$CIBW_MANYLINUX_IMAGE"
    CIBW_BEFORE_ALL="$CIBW_BEFORE_ALL"
    CIBW_TEST_COMMAND="$CIBW_TEST_COMMAND"
    TVM_PKG_VERSION="$TVM_PKG_VERSION" 
    TVM_INSTALL_PREFIX="$TVM_INSTALL_PREFIX" 
    TVM_LIBRARY_PATH="$TVM_LIBRARY_PATH" 
    TVM_EXTRA_LIB_LIST="$TVM_EXTRA_LIB_LIST" 
    CIBW_ENVIRONMENT_PASS="TVM_PKG_VERSION TVM_INSTALL_PREFIX TVM_LIBRARY_PATH TVM_EXTRA_LIB_LIST" 
    CIBW_BUILD_VERBOSITY=1
    CIBW_DEBUG_KEEP_CONTAINER="$CIBW_DEBUG_KEEP_CONTAINER"
)

if [ -n "$CIBW_CONTAINER_ENGINE_ARG" ]; then
    ENV_VARS+=("$CIBW_CONTAINER_ENGINE_ARG")
fi

env "${ENV_VARS[@]}" \
      cibuildwheel \
      tvm/python

# For debug:
#    CIBW_DEBUG_KEEP_CONTAINER=1 \
#    CIBW_BUILD_VERBOSITY=1 \
